### ISSUE TITLE
Save tweets in case of unexpected exit

### ISSUE THREAD

**Issue by hugovk** [dicksonleong/Tweetian#2]
Tweetian 1.6.0
Nokia 808 Belle FP2

I usually have Tweetian running all the time, and keep up with the latest tweets.

Sometimes after the phone turns itself off (e.g. battery runs out or a random reboot), when I restart Tweetian it shows the tweets back from start of the last session, rather from near the end of the last session.

It would be nice if it could periodically save its position, the same way it does when exiting normally from within the application. Perhaps it could do this the same time it periodically updates tweets from the network.

I know it's easy to press the tab to skip to the most recent, and mark all read, but especially if some time has passed from exit to restart, then you would have to scroll back to see what you missed.

**Comment by dicksonleong** [comment]
Edit the title a bit: should be save tweets instead of save position.

For improve performance, the tweets are only save to database when app is exiting. When tweets are saving to database, the UI can freeze for 1~3 seconds so if I save the tweets periodically it could cause the UI freeze periodically (and battery drainage too if leave it in the background for long time)

**Comment by denseacat** [comment]
@dicksonleong But I think this will be useful. Just save every N minutes(user customisable number), if phone is locked. I think it will be a good idea - include this function in "Experimental" options section, and turn it off by the default.
